version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: tellus_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tellusdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: tellus_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/tellusdb?schema=public"
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
